### ISSUE TITLE
HQ1アルバトロスのパッシブ2「レーダー管制」の回避率バフ値ミスの疑い

### ISSUE THREAD

**Issue by ilovean2003iron** [harry0000/last-origin-unit-viewer#56]
本ツールによると、HQ1アルバトロスのパッシブ2「レーダー管制」スキルLv10で、「ラウンド開始時、自分が「出力制限解除装置」を装備している / 「改良型出力制限解除装置」を装備している / 「HQ1コマンダーシステム」を装備している場合」に働く効果として、「回避率 +29%」が記載されているが、滅亡前の戦術教本( https://lo.swaytwig.com/ )によると、同パッシブにより働く同効果は、「回避率 +66%」と記載されており、矛盾が生じている。
![image](https://user-images.githubusercontent.com/76030446/217281913-5e1d32bc-d67f-4bb6-a5b1-51cc7f43c98f.png)
![image](https://user-images.githubusercontent.com/76030446/217282100-68d93219-a75b-4812-ae49-42cf893a534a.png)

**Comment by harry0000** [comment]
バグ報告ありがとうございます。ゲーム内で回避率の上昇値が30～66%であることを確認しました。そのため次回のリリース(v1.2.0)で修正します。

![LastOrigin_R 2023_02_08 1_40_25](https://user-images.githubusercontent.com/3132512/217311150-804e3f46-9ff4-4fcc-9145-f7cd7cc6d041.png)

In English:
Thank you for the bug report. I have confirmed that the increase in evasion rate is 30～66% in the game. Therefore, I will fix it in the next release (v1.2.0).
